// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQgEbgwqqXOqeXKudY211ESIOzK_Im934',
    appId: '1:743951780713:web:a2b87f322356347591cbf8',
    messagingSenderId: '743951780713',
    projectId: 'spaces-application',
    authDomain: 'spaces-application.firebaseapp.com',
    databaseURL: 'https://spaces-application-default-rtdb.firebaseio.com',
    storageBucket: 'spaces-application.appspot.com',
    measurementId: 'G-BPCJ3X2NZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVbzQQo6C0iFfN7XL6GKrqRx-7FXz8Ngw',
    appId: '1:743951780713:android:b683730b17cc373691cbf8',
    messagingSenderId: '743951780713',
    projectId: 'spaces-application',
    databaseURL: 'https://spaces-application-default-rtdb.firebaseio.com',
    storageBucket: 'spaces-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxiBES7VgJjb6ZMjvW8MP2Gr1NV3RlwY',
    appId: '1:743951780713:ios:e4b276c766257fbd91cbf8',
    messagingSenderId: '743951780713',
    projectId: 'spaces-application',
    databaseURL: 'https://spaces-application-default-rtdb.firebaseio.com',
    storageBucket: 'spaces-application.appspot.com',
    iosClientId: '743951780713-n6d5v4shtafreg88giiu822tv77dg8h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxiBES7VgJjb6ZMjvW8MP2Gr1NV3RlwY',
    appId: '1:743951780713:ios:e4b276c766257fbd91cbf8',
    messagingSenderId: '743951780713',
    projectId: 'spaces-application',
    databaseURL: 'https://spaces-application-default-rtdb.firebaseio.com',
    storageBucket: 'spaces-application.appspot.com',
    iosClientId: '743951780713-n6d5v4shtafreg88giiu822tv77dg8h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacesApplication',
  );
}
